### ISSUE TITLE
l.some is not a function error

### ISSUE THREAD

**Issue by providentitsolutions** [KelvinTegelaar/CIPP#3216]
### Description

Since updating to v7.0.1 the frontend will load but you're pretty much unable to do anything as within a few seconds you get a popup modal that says "l.some is not a function"

![image](https://github.com/user-attachments/assets/4da3aabe-14e7-4bb9-9404-589974f053fb)

And in the browser console:

![image](https://github.com/user-attachments/assets/db335053-c5cf-44ee-9983-6edc489bb613)

I've tried restarting the function app and clearing all cache from CIPP > Settings, but no joy

### Environment data

```PowerShell
Non-sponsored instance
Front end version number: v7.0.2
Back end version number: v7.0.2
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by MosesCom** [comment]
Same error here.

**Comment by GreenvalleyIT** [comment]
Same here

**Comment by KelvinTegelaar** [comment]
fixed in dev
